#!/bin/sh

FFS_HOME=/home/xiaobingo/IIT-study/course/cs495/proj5/fusionfs

FFS_SRC_HOME=$FFS_HOME/src

#start the service for file transfer
#/home/dzhao/fusionfs/src/ffsnet/ffsnetd 2>&1 1>/dev/null &
$FFS_SRC_HOME/ffsnet/ffsnetd 2>&1 1>/dev/null &    

#start the service for ZHT server
#/home/dzhao/fusionfs/src/zht/bin/server_zht 50000 /home/dzhao/fusionfs/src/zht/neighbor /home/dzhao/fusionfs/src/zht/zht.cfg TCP 2>&1 1>/dev/null &
$FFS_SRC_HOME/zht/bin/server_zht 50000 $FFS_SRC_HOME/zht/neighbor $FFS_SRC_HOME/zht/zht.cfg TCP 2>&1 1>/dev/null &
$FFS_SRC_HOME/zht/bin/server_zht 50001 $FFS_SRC_HOME/zht/neighbor $FFS_SRC_HOME/zht/zht.cfg TCP 2>&1 1>/dev/null &
