#!/bin/sh

#/home/dzhao/fusionfs/src/fusionfs /tmp /home/dzhao/fusion_mount

HOME_DIR=/home/xiaobingo/cs495proj5

FFS_SRC_HOME=/home/xiaobingo/IIT-study/course/cs495/proj5/fusionfs/src

$FFS_SRC_HOME/fusionfs $HOME_DIR/tmp $HOME_DIR/fusion_mount


